from __future__ import annotations

import os
import re
import shutil
import zlib
from pathlib import Path
from typing import Any, Callable

from agent.db import Store
from agent.logutil import get_logger
from agent.support import record_is_enabled
from agent.support.process import run

log = get_logger("peer_egress")

Runner = Callable[..., Any]

_IFACE_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_.-]{0,14}$")
_STATE_KIND = "egress_state"
_STATE_ID = "applied"
_IFACE_KIND = "interface"
_NFT_CHAIN = "postrouting"
_MASQ_COMMENT_PREFIX = "netinja-egress:"
_UNIT_NAME = "agent-peer-egress.service"
_UNIT_PATH = Path("/etc/systemd/system") / _UNIT_NAME
_EGRESS_CORES = ("wireguard", "amnezia")


def table_id_for_interface(name: str) -> int:
    digest = zlib.crc32(name.encode("utf-8")) & 0xFFFF
    return 10000 + (digest % 20000)


def normalize_exit_interface(value: Any) -> str | None:
    name = str(value or "").strip()
    if not name:
        return None
    if not _IFACE_RE.match(name):
        return None
    return name


def peer_source_cidr(address: Any) -> str | None:
    text = str(address or "").strip()
    if not text:
        return None
    host = text.split("/", 1)[0].strip()
    if not host:
        return None
    return f"{host}/32"


def apply_script_path(data_dir: str | Path | None = None) -> Path:
    base = Path(data_dir or os.environ.get("DATA_DIR") or "/var/lib/agent")
    return base / "peer-egress-apply.sh"


def desired_rules_from_interfaces(interfaces: list[dict[str, Any]]) -> list[dict[str, str | int]]:
    rules: list[dict[str, str | int]] = []
    seen: set[str] = set()
    for iface in interfaces:
        for peer in iface.get("peers") or []:
            if not isinstance(peer, dict) or not record_is_enabled(peer):
                continue
            exit_iface = normalize_exit_interface(peer.get("exit_interface"))
            cidr = peer_source_cidr(peer.get("address"))
            if not exit_iface or not cidr:
                continue
            addr = cidr.split("/", 1)[0]
            if addr in seen:
                continue
            seen.add(addr)
            rules.append(
                {
                    "addr": addr,
                    "cidr": cidr,
                    "iface": exit_iface,
                    "table": table_id_for_interface(exit_iface),
                }
            )
    return rules


def all_desired_rules_from_store(store: Store) -> list[dict[str, str | int]]:
    """Prefer live interface docs; fall back to last applied egress_state."""
    merged: list[dict[str, str | int]] = []
    seen: set[str] = set()
    for core in _EGRESS_CORES:
        ifaces = store.list_docs(core, _IFACE_KIND)
        if ifaces:
            source = desired_rules_from_interfaces(ifaces)
        else:
            state = store.get_doc(core, _STATE_KIND, _STATE_ID) or {}
            source = []
            for row in state.get("rules") or []:
                if not isinstance(row, dict):
                    continue
                addr = str(row.get("addr") or "").strip()
                iface = str(row.get("iface") or "").strip()
                table = int(row.get("table") or 0)
                if not addr or not iface or table <= 0:
                    continue
                source.append(
                    {
                        "addr": addr,
                        "cidr": f"{addr}/32",
                        "iface": iface,
                        "table": table,
                    }
                )
        for row in source:
            addr = str(row["addr"])
            if addr in seen:
                continue
            seen.add(addr)
            merged.append(row)
    return merged


def render_apply_script(rules: list[dict[str, str | int]]) -> str:
    """Self-contained shell script so egress survives reboot (wg-quick PostUp / systemd)."""
    lines = [
        "#!/bin/sh",
        "# Generated by Netinja agent — peer egress policy routing. Do not edit.",
        "set +e",
        "sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true",
        "",
        '_default_for_iface() {',
        '  iface="$1"',
        '  table="$2"',
        '  via="$(ip -4 route show default 2>/dev/null | awk -v d="$iface" \'$0 ~ "dev "d {for(i=1;i<=NF;i++) if($i=="via"){print $(i+1); exit}}\')"',
        '  if [ -n "$via" ]; then',
        '    ip route replace default via "$via" dev "$iface" table "$table" 2>/dev/null || true',
        '  else',
        '    ip route replace default dev "$iface" table "$table" 2>/dev/null || true',
        '  fi',
        '}',
        "",
    ]

    tables: dict[int, str] = {}
    masq: set[str] = set()
    for row in rules:
        addr = str(row["addr"])
        cidr = str(row.get("cidr") or f"{addr}/32")
        table = int(row["table"])
        iface = str(row["iface"])
        tables[table] = iface
        masq.add(iface)
        lines.append(f'ip rule del from "{cidr}" lookup {table} 2>/dev/null || true')
        lines.append(f'ip rule add from "{cidr}" lookup {table} 2>/dev/null || true')

    lines.append("")
    for table, iface in sorted(tables.items()):
        lines.append(f'_default_for_iface "{iface}" {table}')

    lines.append("")
    # Prefer nft at apply-time; fall back to iptables inside the script.
    lines.extend(
        [
            "if command -v nft >/dev/null 2>&1; then",
            "  nft add table inet netinja_egress 2>/dev/null || true",
            "  nft add chain inet netinja_egress postrouting "
            '"{ type nat hook postrouting priority srcnat; policy accept; }" 2>/dev/null || true',
            "  nft add chain inet netinja_egress forward "
            '"{ type filter hook forward priority filter; policy accept; }" 2>/dev/null || true',
            "  nft flush chain inet netinja_egress postrouting 2>/dev/null || true",
            "  nft flush chain inet netinja_egress forward 2>/dev/null || true",
        ]
    )
    for iface in sorted(masq):
        comment = f"{_MASQ_COMMENT_PREFIX}{iface}"
        lines.append(
            f'  nft add rule inet netinja_egress postrouting oifname "{iface}" '
            f'masquerade comment "{comment}" 2>/dev/null || true'
        )
        lines.append(
            f'  nft add rule inet netinja_egress forward oifname "{iface}" '
            f'accept comment "{comment}-fwd-out" 2>/dev/null || true'
        )
        lines.append(
            f'  nft add rule inet netinja_egress forward iifname "{iface}" '
            f'ct state related,established accept comment "{comment}-fwd-in" 2>/dev/null || true'
        )
    lines.append("elif command -v iptables >/dev/null 2>&1; then")
    for iface in sorted(masq):
        comment = f"{_MASQ_COMMENT_PREFIX}{iface}"
        lines.append(
            f'  iptables -t nat -C POSTROUTING -o "{iface}" -m comment --comment "{comment}" '
            f"-j MASQUERADE 2>/dev/null || "
            f'iptables -t nat -A POSTROUTING -o "{iface}" -m comment --comment "{comment}" -j MASQUERADE'
        )
        lines.append(
            f'  iptables -C FORWARD -o "{iface}" -m comment --comment "{comment}-fwd-out" -j ACCEPT 2>/dev/null || '
            f'iptables -I FORWARD 1 -o "{iface}" -m comment --comment "{comment}-fwd-out" -j ACCEPT'
        )
        lines.append(
            f'  iptables -C FORWARD -i "{iface}" -m state --state RELATED,ESTABLISHED '
            f'-m comment --comment "{comment}-fwd-in" -j ACCEPT 2>/dev/null || '
            f'iptables -I FORWARD 1 -i "{iface}" -m state --state RELATED,ESTABLISHED '
            f'-m comment --comment "{comment}-fwd-in" -j ACCEPT'
        )
    lines.append("fi")
    lines.append("")

    lines.append("exit 0")
    return "\n".join(lines) + "\n"


def write_apply_script(rules: list[dict[str, str | int]], *, data_dir: str | Path | None = None) -> Path:
    path = apply_script_path(data_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_apply_script(rules), encoding="utf-8")
    try:
        path.chmod(0o755)
    except OSError:
        pass
    return path


def ensure_peer_egress_unit(script_path: Path, *, runner: Runner | None = None) -> dict[str, Any]:
    """Install/enable a oneshot systemd unit that restores egress after reboot."""
    execute = runner or run
    if not shutil.which("systemctl"):
        return {"ok": False, "skipped": True, "reason": "systemctl not found"}

    unit = "\n".join(
        [
            "[Unit]",
            "Description=Netinja peer egress routing (WireGuard/Amnezia)",
            "After=network-online.target",
            "Wants=network-online.target",
            "",
            "[Service]",
            "Type=oneshot",
            f"ExecStart={script_path}",
            "RemainAfterExit=yes",
            "",
            "[Install]",
            "WantedBy=multi-user.target",
            "",
        ]
    )

    try:
        _UNIT_PATH.parent.mkdir(parents=True, exist_ok=True)
        previous = _UNIT_PATH.read_text(encoding="utf-8") if _UNIT_PATH.is_file() else ""
        if previous != unit:
            _UNIT_PATH.write_text(unit, encoding="utf-8")
            execute(["systemctl", "daemon-reload"], check=False, timeout=30)
    except OSError as exc:
        log.warning("peer egress unit write failed: %s", exc)
        return {"ok": False, "skipped": False, "reason": str(exc)}

    enable = execute(["systemctl", "enable", _UNIT_NAME], check=False, timeout=30)
    return {
        "ok": getattr(enable, "returncode", 1) == 0,
        "unit": str(_UNIT_PATH),
        "script": str(script_path),
    }


def persist_peer_egress(store: Store, *, data_dir: str | Path | None = None, runner: Runner | None = None) -> dict[str, Any]:
    rules = all_desired_rules_from_store(store)
    script = write_apply_script(rules, data_dir=data_dir)
    unit = ensure_peer_egress_unit(script, runner=runner)
    return {"script": str(script), "rules": len(rules), "unit": unit}


def reconcile_core_egress(
    store: Store,
    core: str,
    interfaces: list[dict[str, Any]],
    *,
    runner: Runner | None = None,
    data_dir: str | Path | None = None,
) -> dict[str, Any]:
    execute = runner or run
    if not shutil.which("ip"):
        return {"ok": False, "skipped": True, "reason": "ip not found"}

    desired = desired_rules_from_interfaces(interfaces)
    previous = store.get_doc(core, _STATE_KIND, _STATE_ID) or {}
    prev_rules = [row for row in (previous.get("rules") or []) if isinstance(row, dict)]

    desired_keys = {(str(row["addr"]), int(row["table"]), str(row["iface"])) for row in desired}

    _ensure_ip_forward(execute)

    # Drop stale rules that are no longer desired.
    for row in prev_rules:
        key = (str(row.get("addr") or ""), int(row.get("table") or 0), str(row.get("iface") or ""))
        if key in desired_keys:
            continue
        cidr = peer_source_cidr(row.get("addr")) or f"{row.get('addr')}/32"
        table = int(row.get("table") or 0)
        if table:
            _ip(execute, ["rule", "del", "from", cidr, "lookup", str(table)])

    # Always re-apply desired rules (SQLite may say "applied" while OS lost them after reboot).
    for row in desired:
        cidr = str(row["cidr"])
        table = str(row["table"])
        _ip(execute, ["rule", "del", "from", cidr, "lookup", table])
        _ip(execute, ["rule", "add", "from", cidr, "lookup", table])

    desired_tables = {int(row["table"]): str(row["iface"]) for row in desired}
    prev_tables = {
        int(row.get("table") or 0): str(row.get("iface") or "")
        for row in prev_rules
        if int(row.get("table") or 0) > 0
    }

    for table, iface in desired_tables.items():
        _install_default_route(execute, iface=iface, table=table)

    for table in prev_tables:
        if table not in desired_tables:
            _ip(execute, ["route", "flush", "table", str(table)])

    masq_ifaces = sorted({str(row["iface"]) for row in desired})
    # Merge masq with other cores so we don't drop shared exits while reconciling one core.
    other_masq: set[str] = set()
    for other in _EGRESS_CORES:
        if other == core:
            continue
        other_state = store.get_doc(other, _STATE_KIND, _STATE_ID) or {}
        for iface in other_state.get("masq") or []:
            name = str(iface or "").strip()
            if name:
                other_masq.add(name)
    effective_masq = sorted(set(masq_ifaces) | other_masq)
    previous_masq = list(previous.get("masq") or [])
    for iface in other_masq:
        if iface not in previous_masq:
            previous_masq.append(iface)
    _sync_masquerade(effective_masq, previous_ifaces=previous_masq, runner=execute)
    _sync_forward(effective_masq, previous_ifaces=previous_masq, runner=execute)

    state = {
        "rules": [
            {"addr": str(row["addr"]), "table": int(row["table"]), "iface": str(row["iface"])}
            for row in desired
        ],
        "tables": sorted(desired_tables.keys()),
        "masq": masq_ifaces,
    }
    store.put_doc(core, _STATE_KIND, _STATE_ID, state)

    persist = persist_peer_egress(store, data_dir=data_dir, runner=execute)
    return {
        "ok": True,
        "skipped": False,
        "rules": len(desired),
        "masq": masq_ifaces,
        "persist": persist,
    }


def _ip(runner: Runner, args: list[str]) -> None:
    try:
        result = runner(["ip", *args], check=False, timeout=10)
    except Exception as exc:
        log.warning("ip %s failed: %s", " ".join(args), exc)
        return
    if getattr(result, "returncode", 1) != 0:
        stderr = (getattr(result, "stderr", None) or getattr(result, "stdout", None) or "").strip()
        # delete of missing rule is expected
        if args[:1] == ["rule"] and "del" in args:
            return
        log.warning("ip %s rc=%s %s", " ".join(args), getattr(result, "returncode", "?"), stderr)


def _install_default_route(runner: Runner, *, iface: str, table: int) -> None:
    """Prefer `default via <gw> dev <iface>` when main table has a gateway on that NIC."""
    via = _gateway_for_iface(runner, iface)
    if via:
        _ip(runner, ["route", "replace", "default", "via", via, "dev", iface, "table", str(table)])
        return
    _ip(runner, ["route", "replace", "default", "dev", iface, "table", str(table)])


def _gateway_for_iface(runner: Runner, iface: str) -> str | None:
    try:
        result = runner(["ip", "-4", "route", "show", "default"], check=False, timeout=5)
    except Exception:
        return None
    if getattr(result, "returncode", 1) != 0:
        return None
    stdout = str(getattr(result, "stdout", "") or "")
    for line in stdout.splitlines():
        parts = line.split()
        if "dev" not in parts:
            continue
        try:
            dev = parts[parts.index("dev") + 1]
        except (ValueError, IndexError):
            continue
        if dev != iface:
            continue
        if "via" in parts:
            try:
                return parts[parts.index("via") + 1]
            except (ValueError, IndexError):
                return None
        return None
    return None


def _ensure_ip_forward(runner: Runner) -> None:
    try:
        path = "/proc/sys/net/ipv4/ip_forward"
        with open(path, "w", encoding="utf-8") as handle:
            handle.write("1\n")
        return
    except OSError:
        pass
    if shutil.which("sysctl"):
        try:
            runner(["sysctl", "-w", "net.ipv4.ip_forward=1"], check=False, timeout=5)
        except Exception:
            pass


def _sync_masquerade(ifaces: list[str], *, previous_ifaces: list[str], runner: Runner) -> None:
    backend = "nft" if shutil.which("nft") else ("iptables" if shutil.which("iptables") else "")
    if backend == "nft":
        _sync_masquerade_nft(ifaces, runner=runner)
        return
    if backend == "iptables":
        _sync_masquerade_iptables(ifaces, previous_ifaces=previous_ifaces, runner=runner)


def _sync_forward(ifaces: list[str], *, previous_ifaces: list[str], runner: Runner) -> None:
    # nft FORWARD rules are installed inside _sync_masquerade_nft; only iptables needs a separate pass.
    if shutil.which("nft"):
        return
    if shutil.which("iptables"):
        _sync_forward_iptables(ifaces, previous_ifaces=previous_ifaces, runner=runner)


def _sync_forward_iptables(ifaces: list[str], *, previous_ifaces: list[str], runner: Runner) -> None:
    wanted = set(ifaces)
    for iface in previous_ifaces:
        if iface in wanted:
            continue
        for comment, args in (
            (f"{_MASQ_COMMENT_PREFIX}{iface}-fwd-out", ["-o", iface]),
            (f"{_MASQ_COMMENT_PREFIX}{iface}-fwd-in", ["-i", iface, "-m", "state", "--state", "RELATED,ESTABLISHED"]),
        ):
            _iptables(
                runner,
                ["-D", "FORWARD", *args, "-m", "comment", "--comment", comment, "-j", "ACCEPT"],
            )
    for iface in ifaces:
        out_comment = f"{_MASQ_COMMENT_PREFIX}{iface}-fwd-out"
        in_comment = f"{_MASQ_COMMENT_PREFIX}{iface}-fwd-in"
        if not _iptables(
            runner,
            ["-C", "FORWARD", "-o", iface, "-m", "comment", "--comment", out_comment, "-j", "ACCEPT"],
            quiet=True,
        ):
            _iptables(
                runner,
                ["-I", "FORWARD", "1", "-o", iface, "-m", "comment", "--comment", out_comment, "-j", "ACCEPT"],
            )
        if not _iptables(
            runner,
            [
                "-C",
                "FORWARD",
                "-i",
                iface,
                "-m",
                "state",
                "--state",
                "RELATED,ESTABLISHED",
                "-m",
                "comment",
                "--comment",
                in_comment,
                "-j",
                "ACCEPT",
            ],
            quiet=True,
        ):
            _iptables(
                runner,
                [
                    "-I",
                    "FORWARD",
                    "1",
                    "-i",
                    iface,
                    "-m",
                    "state",
                    "--state",
                    "RELATED,ESTABLISHED",
                    "-m",
                    "comment",
                    "--comment",
                    in_comment,
                    "-j",
                    "ACCEPT",
                ],
            )


def _sync_masquerade_nft(ifaces: list[str], *, runner: Runner) -> None:
    _nft(runner, ["add", "table", "inet", "netinja_egress"])
    _nft(
        runner,
        [
            "add",
            "chain",
            "inet",
            "netinja_egress",
            _NFT_CHAIN,
            "{ type nat hook postrouting priority srcnat; policy accept; }",
        ],
    )
    _nft(
        runner,
        [
            "add",
            "chain",
            "inet",
            "netinja_egress",
            "forward",
            "{ type filter hook forward priority filter; policy accept; }",
        ],
    )
    _nft(runner, ["flush", "chain", "inet", "netinja_egress", _NFT_CHAIN])
    _nft(runner, ["flush", "chain", "inet", "netinja_egress", "forward"])
    for iface in ifaces:
        _nft(
            runner,
            [
                "add",
                "rule",
                "inet",
                "netinja_egress",
                _NFT_CHAIN,
                "oifname",
                iface,
                "masquerade",
                "comment",
                f"{_MASQ_COMMENT_PREFIX}{iface}",
            ],
        )
        _nft(
            runner,
            [
                "add",
                "rule",
                "inet",
                "netinja_egress",
                "forward",
                "oifname",
                iface,
                "accept",
                "comment",
                f"{_MASQ_COMMENT_PREFIX}{iface}-fwd-out",
            ],
        )
        _nft(
            runner,
            [
                "add",
                "rule",
                "inet",
                "netinja_egress",
                "forward",
                "iifname",
                iface,
                "ct",
                "state",
                "related,established",
                "accept",
                "comment",
                f"{_MASQ_COMMENT_PREFIX}{iface}-fwd-in",
            ],
        )


def _sync_masquerade_iptables(ifaces: list[str], *, previous_ifaces: list[str], runner: Runner) -> None:
    wanted = set(ifaces)
    for iface in previous_ifaces:
        if iface in wanted:
            continue
        comment = f"{_MASQ_COMMENT_PREFIX}{iface}"
        _iptables(
            runner,
            ["-t", "nat", "-D", "POSTROUTING", "-o", iface, "-m", "comment", "--comment", comment, "-j", "MASQUERADE"],
        )
    for iface in ifaces:
        comment = f"{_MASQ_COMMENT_PREFIX}{iface}"
        check = _iptables(
            runner,
            ["-t", "nat", "-C", "POSTROUTING", "-o", iface, "-m", "comment", "--comment", comment, "-j", "MASQUERADE"],
            quiet=True,
        )
        if check:
            continue
        _iptables(
            runner,
            ["-t", "nat", "-A", "POSTROUTING", "-o", iface, "-m", "comment", "--comment", comment, "-j", "MASQUERADE"],
        )


def _nft(runner: Runner, args: list[str]) -> None:
    try:
        result = runner(["nft", *args], check=False, timeout=10)
    except Exception as exc:
        log.warning("nft %s failed: %s", " ".join(args), exc)
        return
    if getattr(result, "returncode", 1) != 0:
        stderr = (getattr(result, "stderr", None) or "").strip().lower()
        if "exist" in stderr:
            return
        log.warning("nft %s rc=%s %s", " ".join(args), getattr(result, "returncode", "?"), stderr)


def _iptables(runner: Runner, args: list[str], *, quiet: bool = False) -> bool:
    try:
        result = runner(["iptables", *args], check=False, timeout=10)
    except Exception as exc:
        if not quiet:
            log.warning("iptables %s failed: %s", " ".join(args), exc)
        return False
    ok = getattr(result, "returncode", 1) == 0
    if not ok and not quiet:
        stderr = (getattr(result, "stderr", None) or "").strip()
        if "does a matching rule exist" not in stderr.lower():
            log.warning("iptables %s rc=%s %s", " ".join(args), getattr(result, "returncode", "?"), stderr)
    return ok
