"""Ads-blocking DNS filter for WireGuard / Amnezia clients via dnsmasq."""

from __future__ import annotations

import os
import shutil
import sys
from pathlib import Path
from typing import Any, Callable

from agent.dns_leak import (
    DNSMASQ_DROPIN,
    discover_vpn_interfaces,
    dns_leak_status,
    dnsmasq_service_active,
    dnsmasq_service_diagnostic,
    ensure_dnsmasq_service,
    ensure_vpn_dns_resolver,
    teardown_vpn_dns_if_unused,
)
from agent.errors import AgentError
from agent.logutil import get_logger
from agent.support.process import run

log = get_logger("ads_block")

ADS_DROPIN = Path("/etc/dnsmasq.d/netinja-ads-block.conf")
ADS_LIST_PATH = Path("/var/lib/agent/ads-blocklist.txt")

Runner = Callable[..., Any]

# Curated high-signal ad / tracker hosts (suffix-style for dnsmasq address=/domain/0.0.0.0).
DEFAULT_ADS_DOMAINS = (
    "doubleclick.net",
    "googleadservices.com",
    "googlesyndication.com",
    "google-analytics.com",
    "googletagmanager.com",
    "googletagservices.com",
    "pagead2.googlesyndication.com",
    "adservice.google.com",
    "connect.facebook.net",
    "ads-twitter.com",
    "ads.twitter.com",
    "static.ads-twitter.com",
    "advertising.com",
    "adsafeprotected.com",
    "adnxs.com",
    "adsrvr.org",
    "adcolony.com",
    "adform.net",
    "admob.com",
    "amazon-adsystem.com",
    "analytics.yahoo.com",
    "bat.bing.com",
    "bidswitch.net",
    "casalemedia.com",
    "chartbeat.com",
    "criteo.com",
    "criteo.net",
    "outbrain.com",
    "pubmatic.com",
    "rubiconproject.com",
    "scorecardresearch.com",
    "taboola.com",
    "tapad.com",
    "trafficjunky.net",
    "mc.yandex.ru",
    "advertising.yandex.ru",
    "ads.linkedin.com",
    "snapads.com",
    "moatads.com",
    "openx.net",
    "quantserve.com",
    "serving-sys.com",
    "smartadserver.com",
    "tremorhub.com",
    "yieldmo.com",
)


def _require_linux() -> None:
    if not sys.platform.startswith("linux"):
        raise AgentError("UNSUPPORTED_CAPABILITY", "Ads DNS filter requires Linux")


def _require_root() -> None:
    geteuid = getattr(os, "geteuid", None)
    if geteuid is None or geteuid() != 0:
        raise AgentError("VALIDATION_ERROR", "Ads DNS filter requires root (run with sudo)")


def _load_domains() -> list[str]:
    domains: list[str] = []
    seen: set[str] = set()
    sources = list(DEFAULT_ADS_DOMAINS)
    if ADS_LIST_PATH.is_file():
        try:
            for line in ADS_LIST_PATH.read_text(encoding="utf-8", errors="ignore").splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                sources.append(line)
        except OSError:
            pass

    for item in sources:
        host = item.strip().lower().rstrip(".")
        if not host or host in seen:
            continue
        if any(ch.isspace() for ch in host):
            continue
        seen.add(host)
        domains.append(host)
    return domains


def _vpn_dns_addresses(*, runner: Runner | None = None) -> list[str]:
    addrs: list[str] = []
    try:
        interfaces = discover_vpn_interfaces(runner=runner)
    except AgentError:
        interfaces = []
    for row in interfaces:
        gateway = str(row.get("gateway") or "").strip()
        if gateway:
            addrs.append(gateway)
    return list(dict.fromkeys(addrs))


def render_dnsmasq_ads_conf(domains: list[str]) -> str:
    lines = [
        "# Generated by Netinja agent — ads blocklist for VPN DNS.",
        "# Clients that use this resolver (Interface DNS) get ads NX/blackholed.",
    ]
    for domain in domains:
        lines.append(f"address=/{domain}/0.0.0.0")
    lines.append("")
    return "\n".join(lines)


def _firewall_backend() -> str | None:
    if shutil.which("nft"):
        return "nft"
    if shutil.which("iptables"):
        return "iptables"
    return None


def ads_block_prerequisites(*, runner: Runner | None = None) -> dict[str, Any]:
    if not sys.platform.startswith("linux"):
        return {
            "linux": False,
            "root": False,
            "dnsmasq_installed": False,
            "dnsmasq_active": False,
            "dnsmasq_dropin": False,
            "ads_dropin": ADS_DROPIN.is_file(),
            "firewall_backend": None,
            "nft": False,
            "iptables": False,
            "dig": bool(shutil.which("dig")),
            "apt": bool(shutil.which("apt-get")),
            "vpn_interfaces": [],
            "vpn_interface_count": 0,
            "dns_leak_active": False,
            "dnsmasq_error": None,
            "ready": False,
        }

    vpn_ifaces = discover_vpn_interfaces(runner=runner)
    backend = _firewall_backend()
    dnsmasq_bin = bool(shutil.which("dnsmasq"))
    geteuid = getattr(os, "geteuid", None)
    is_root = geteuid is not None and geteuid() == 0
    dnsmasq_active = dnsmasq_service_active(runner=runner) if dnsmasq_bin else False
    dnsmasq_error = None
    if dnsmasq_bin and not dnsmasq_active:
        dnsmasq_error = dnsmasq_service_diagnostic(runner=runner)

    dns_leak: dict[str, Any] = {}
    try:
        dns_leak = dns_leak_status(runner=runner)
    except AgentError:
        pass

    return {
        "linux": True,
        "root": is_root,
        "dnsmasq_installed": dnsmasq_bin,
        "dnsmasq_active": dnsmasq_active,
        "dnsmasq_dropin": DNSMASQ_DROPIN.is_file(),
        "ads_dropin": ADS_DROPIN.is_file(),
        "firewall_backend": backend,
        "nft": bool(shutil.which("nft")),
        "iptables": bool(shutil.which("iptables")),
        "dig": bool(shutil.which("dig")),
        "apt": bool(shutil.which("apt-get")),
        "vpn_interfaces": vpn_ifaces,
        "vpn_interface_count": len(vpn_ifaces),
        "dns_leak_active": bool(dns_leak.get("active")),
        "dnsmasq_error": dnsmasq_error,
        "ready": (
            dnsmasq_bin
            and dnsmasq_active
            and backend is not None
            and len(vpn_ifaces) > 0
        ),
    }


def ads_block_repair_service(*, runner: Runner | None = None) -> dict[str, Any]:
    """Try to start dnsmasq and fix systemd-resolved port-53 conflicts."""
    _require_linux()
    _require_root()

    service = ensure_dnsmasq_service(runner=runner)
    payload = ads_block_prerequisites(runner=runner)
    payload.update({"ok": bool(service.get("active")), "service": service})
    if not service.get("active"):
        message = str(service.get("diagnostic") or service.get("journal") or "").strip()
        if not message or message == str(service.get("config_message") or "").strip():
            unit = str(service.get("unit_enabled") or "unknown")
            message = f"dnsmasq failed to start (unit: {unit})"
        raise AgentError("VALIDATION_ERROR", message)
    return payload


def ads_block_install_prerequisites(*, runner: Runner | None = None) -> dict[str, Any]:
    """Install dnsmasq (and ensure data dir) required for WireGuard ads blocking."""
    _require_linux()
    _require_root()
    execute = runner or run

    installed: list[str] = []
    if not shutil.which("dnsmasq"):
        apt = shutil.which("apt-get")
        if apt is None:
            raise AgentError(
                "UNSUPPORTED_CAPABILITY",
                "dnsmasq is not installed and apt-get is unavailable; install dnsmasq manually",
            )
        execute([apt, "update", "-qq"], check=False, timeout=120)
        proc = execute([apt, "install", "-y", "-qq", "dnsmasq", "dnsutils"], check=False, timeout=300)
        if proc.returncode != 0 or not shutil.which("dnsmasq"):
            raise AgentError("VALIDATION_ERROR", "Installing dnsmasq failed")
        installed.append("dnsmasq")

    try:
        ADS_LIST_PATH.parent.mkdir(parents=True, exist_ok=True)
        if not ADS_LIST_PATH.is_file():
            ADS_LIST_PATH.write_text("# Extra ads domains (one per line)\n", encoding="utf-8")
    except OSError as exc:
        raise AgentError("VALIDATION_ERROR", f"Cannot prepare ads list path: {exc}") from exc

    service = ensure_dnsmasq_service(runner=runner) if shutil.which("dnsmasq") else None

    payload = ads_block_prerequisites(runner=runner)
    payload.update(
        {
            "ok": True,
            "installed": installed,
            "dnsmasq_restarted": bool((service or {}).get("active")),
            "service": service,
        }
    )
    return payload


def ads_block_test(
    domain: str = "doubleclick.net",
    *,
    runner: Runner | None = None,
) -> dict[str, Any]:
    """Resolve a known ad domain via the suggested VPN DNS address."""
    _require_linux()
    execute = runner or run
    host = str(domain or "").strip().lower().rstrip(".")
    if host == "":
        raise AgentError("VALIDATION_ERROR", "domain is required")

    status = ads_block_status(runner=runner)
    dns = str(status.get("dns") or "").strip()
    if dns == "":
        raise AgentError(
            "VALIDATION_ERROR",
            "No VPN gateway DNS address detected; start WireGuard/Amnezia and retry",
        )

    if not shutil.which("dig"):
        raise AgentError("UNSUPPORTED_CAPABILITY", "dig is required (install dnsutils)")

    proc = execute(["dig", "+time=2", "+tries=1", "+short", f"@{dns}", host], check=False, timeout=15)
    answer = (getattr(proc, "stdout", "") or "").strip().splitlines()
    first = answer[0].strip() if answer else ""
    blocked = first in {"", "0.0.0.0"}

    return {
        "ok": True,
        "domain": host,
        "dns": dns,
        "answer": first or None,
        "blocked": blocked,
        "exit_code": getattr(proc, "returncode", 1),
    }


def ads_block_status(*, runner: Runner | None = None) -> dict[str, Any]:
    dns_list = _vpn_dns_addresses(runner=runner)
    prereq = ads_block_prerequisites(runner=runner)
    return {
        "enabled": ADS_DROPIN.is_file(),
        "dropin": str(ADS_DROPIN),
        "list_path": str(ADS_LIST_PATH),
        "domains": len(_load_domains()) if ADS_DROPIN.is_file() else 0,
        "dns": dns_list[0] if dns_list else None,
        "listen_dns": dns_list[0] if dns_list else None,
        "dns_candidates": dns_list,
        "dnsmasq": bool(shutil.which("dnsmasq")),
        "dnsmasq_active": prereq.get("dnsmasq_active"),
        "dnsmasq_dropin": prereq.get("dnsmasq_dropin"),
        "firewall_backend": prereq.get("firewall_backend"),
        "vpn_interface_count": prereq.get("vpn_interface_count"),
        "ready": prereq.get("ready"),
        "prerequisites": prereq,
    }


def ads_block_ensure(*, runner: Runner | None = None) -> dict[str, Any]:
    _require_linux()
    _require_root()
    execute = runner or run

    if not shutil.which("dnsmasq"):
        raise AgentError(
            "UNSUPPORTED_CAPABILITY",
            "dnsmasq is required for ads DNS filtering (install dnsmasq)",
        )

    domains = _load_domains()
    ADS_DROPIN.parent.mkdir(parents=True, exist_ok=True)
    ADS_DROPIN.write_text(render_dnsmasq_ads_conf(domains), encoding="utf-8")

    if not ADS_LIST_PATH.is_file():
        try:
            ADS_LIST_PATH.parent.mkdir(parents=True, exist_ok=True)
            ADS_LIST_PATH.write_text(
                "# Extra ads domains (one per line)\n",
                encoding="utf-8",
            )
        except OSError:
            pass

    vpn_ifaces = discover_vpn_interfaces(runner=runner)
    resolver: dict[str, Any] | None = None
    restarted = False

    if vpn_ifaces:
        try:
            resolver = ensure_vpn_dns_resolver(interfaces=vpn_ifaces, runner=runner)
            restarted = bool((resolver.get("resolver") or {}).get("restarted"))
        except AgentError as exc:
            log.warning("ads_block ensure: VPN DNS resolver setup failed: %s", exc)
        except Exception as exc:
            log.warning("ads_block ensure: VPN DNS resolver setup failed: %s", exc)

    service = ensure_dnsmasq_service(runner=runner) if shutil.which("dnsmasq") else None
    restarted = bool((service or {}).get("active"))

    status = ads_block_status(runner=runner)
    status.update(
        {
            "ok": bool(status.get("ready")),
            "written": True,
            "domains": len(domains),
            "restarted": restarted,
            "resolver": resolver,
            "service": service,
        }
    )
    if not status.get("dnsmasq_active"):
        log.warning(
            "ads_block ensure: dnsmasq is not active — run: sudo agent ads-block repair (%s)",
            (service or {}).get("journal") or (service or {}).get("config_message") or "unknown",
        )
    if not status.get("dns"):
        log.warning("ads_block ensure: no VPN interface DNS address detected yet")
    elif not resolver:
        log.warning(
            "ads_block ensure: ads list written but VPN DNS resolver was not configured; "
            "clients may not reach dnsmasq on %s",
            status.get("dns"),
        )
    return status


def ads_block_disable(*, runner: Runner | None = None) -> dict[str, Any]:
    _require_linux()
    _require_root()
    execute = runner or run

    removed = False
    if ADS_DROPIN.is_file():
        ADS_DROPIN.unlink()
        removed = True

    cleanup = teardown_vpn_dns_if_unused(runner=runner)

    if shutil.which("systemctl") and (removed or cleanup.get("removed_files")):
        execute(["systemctl", "try-reload-or-restart", "dnsmasq"], check=False, timeout=30)

    return {
        "ok": True,
        "removed": removed,
        "cleanup": cleanup,
        **ads_block_status(runner=runner),
    }
