"""Ads-blocking DNS filter for WireGuard / Amnezia clients via dnsmasq."""

from __future__ import annotations

import ipaddress
import os
import shutil
import sys
from pathlib import Path
from typing import Any, Callable

from agent.dns_leak import discover_vpn_interfaces
from agent.errors import AgentError
from agent.logutil import get_logger
from agent.support.process import run

log = get_logger("ads_block")

ADS_DROPIN = Path("/etc/dnsmasq.d/netinja-ads-block.conf")
ADS_LIST_PATH = Path("/var/lib/agent/ads-blocklist.txt")

Runner = Callable[..., Any]

# Curated high-signal ad / tracker hosts (suffix-style for dnsmasq address=/domain/0.0.0.0).
DEFAULT_ADS_DOMAINS = (
    "doubleclick.net",
    "googleadservices.com",
    "googlesyndication.com",
    "google-analytics.com",
    "googletagmanager.com",
    "googletagservices.com",
    "pagead2.googlesyndication.com",
    "adservice.google.com",
    "connect.facebook.net",
    "ads-twitter.com",
    "ads.twitter.com",
    "static.ads-twitter.com",
    "advertising.com",
    "adsafeprotected.com",
    "adnxs.com",
    "adsrvr.org",
    "adcolony.com",
    "adform.net",
    "admob.com",
    "amazon-adsystem.com",
    "analytics.yahoo.com",
    "bat.bing.com",
    "bidswitch.net",
    "casalemedia.com",
    "chartbeat.com",
    "criteo.com",
    "criteo.net",
    "outbrain.com",
    "pubmatic.com",
    "rubiconproject.com",
    "scorecardresearch.com",
    "taboola.com",
    "tapad.com",
    "trafficjunky.net",
    "mc.yandex.ru",
    "advertising.yandex.ru",
    "ads.linkedin.com",
    "snapads.com",
    "moatads.com",
    "openx.net",
    "quantserve.com",
    "serving-sys.com",
    "smartadserver.com",
    "tremorhub.com",
    "yieldmo.com",
)


def _require_linux() -> None:
    if not sys.platform.startswith("linux"):
        raise AgentError("UNSUPPORTED_CAPABILITY", "Ads DNS filter requires Linux")


def _require_root() -> None:
    geteuid = getattr(os, "geteuid", None)
    if geteuid is None or geteuid() != 0:
        raise AgentError("VALIDATION_ERROR", "Ads DNS filter requires root (run with sudo)")


def _load_domains() -> list[str]:
    domains: list[str] = []
    seen: set[str] = set()
    sources = list(DEFAULT_ADS_DOMAINS)
    if ADS_LIST_PATH.is_file():
        try:
            for line in ADS_LIST_PATH.read_text(encoding="utf-8", errors="ignore").splitlines():
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                sources.append(line)
        except OSError:
            pass

    for item in sources:
        host = item.strip().lower().rstrip(".")
        if not host or host in seen:
            continue
        if any(ch.isspace() for ch in host):
            continue
        seen.add(host)
        domains.append(host)
    return domains


def _vpn_dns_addresses(*, runner: Runner | None = None) -> list[str]:
    addrs: list[str] = []
    try:
        interfaces = discover_vpn_interfaces(runner=runner)
    except AgentError:
        interfaces = []
    for row in interfaces:
        for item in row.get("addresses") or []:
            text = str(item).strip()
            if not text:
                continue
            try:
                network = ipaddress.ip_network(text, strict=False)
            except ValueError:
                continue
            if isinstance(network, ipaddress.IPv4Network):
                addrs.append(str(network.network_address))
    return list(dict.fromkeys(addrs))


def render_dnsmasq_ads_conf(domains: list[str]) -> str:
    lines = [
        "# Generated by Netinja agent — ads blocklist for VPN DNS.",
        "# Clients that use this resolver (Interface DNS) get ads NX/blackholed.",
    ]
    for domain in domains:
        lines.append(f"address=/{domain}/0.0.0.0")
    lines.append("")
    return "\n".join(lines)


def ads_block_status(*, runner: Runner | None = None) -> dict[str, Any]:
    dns_list = _vpn_dns_addresses(runner=runner)
    return {
        "enabled": ADS_DROPIN.is_file(),
        "dropin": str(ADS_DROPIN),
        "list_path": str(ADS_LIST_PATH),
        "domains": len(_load_domains()) if ADS_DROPIN.is_file() else 0,
        "dns": dns_list[0] if dns_list else None,
        "listen_dns": dns_list[0] if dns_list else None,
        "dns_candidates": dns_list,
        "dnsmasq": bool(shutil.which("dnsmasq")),
    }


def ads_block_ensure(*, runner: Runner | None = None) -> dict[str, Any]:
    _require_linux()
    _require_root()
    execute = runner or run

    if not shutil.which("dnsmasq"):
        raise AgentError(
            "UNSUPPORTED_CAPABILITY",
            "dnsmasq is required for ads DNS filtering (install dnsmasq)",
        )

    domains = _load_domains()
    ADS_DROPIN.parent.mkdir(parents=True, exist_ok=True)
    ADS_DROPIN.write_text(render_dnsmasq_ads_conf(domains), encoding="utf-8")

    if not ADS_LIST_PATH.is_file():
        try:
            ADS_LIST_PATH.parent.mkdir(parents=True, exist_ok=True)
            ADS_LIST_PATH.write_text(
                "# Extra ads domains (one per line)\n",
                encoding="utf-8",
            )
        except OSError:
            pass

    restarted = False
    if shutil.which("systemctl"):
        result = execute(["systemctl", "try-reload-or-restart", "dnsmasq"], check=False, timeout=30)
        restarted = getattr(result, "returncode", 1) == 0

    status = ads_block_status(runner=runner)
    status.update(
        {
            "ok": True,
            "written": True,
            "domains": len(domains),
            "restarted": restarted,
        }
    )
    if not status.get("dns"):
        log.warning("ads_block ensure: no VPN interface DNS address detected yet")
    return status


def ads_block_disable(*, runner: Runner | None = None) -> dict[str, Any]:
    _require_linux()
    _require_root()
    execute = runner or run

    removed = False
    if ADS_DROPIN.is_file():
        ADS_DROPIN.unlink()
        removed = True

    if shutil.which("systemctl") and removed:
        execute(["systemctl", "try-reload-or-restart", "dnsmasq"], check=False, timeout=30)

    return {"ok": True, "removed": removed, **ads_block_status(runner=runner)}
